#!/usr/bin/env python3
"""
scripts/defense_demo.py

One-command defense demo. Reads the canonical metrics from
results/CANONICAL_METRICS.json (single source of truth) and produces:

  - stdout summary suitable for defense day
  - results/DEFENSE_RUN_SUMMARY.md (auto-regenerated; never hand-edit)

The canonical file is REQUIRED. If it is missing or unreadable, this script
exits with a clear error so that nobody can accidentally present stale or
hardcoded numbers at the defense.

Usage from repository root:
  python scripts/defense_demo.py
  python scripts/defense_demo.py --mode quick
  python scripts/defense_demo.py --mode quick --include-fewshot
  python scripts/defense_demo.py --mode full
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
TABLES = RESULTS / "tables"
SUMMARY_PATH = RESULTS / "DEFENSE_RUN_SUMMARY.md"
CANONICAL_PATH = RESULTS / "CANONICAL_METRICS.json"


def ts() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def load_canonical() -> dict:
    """Load canonical metrics. Fail loudly if missing — this is intentional."""
    if not CANONICAL_PATH.exists():
        print(
            "ERROR: results/CANONICAL_METRICS.json is missing.\n"
            "       Defense demo refuses to invent numbers. To regenerate, see\n"
            "       docs/FINAL_CLEANUP_AUDIT.md and re-create the canonical file\n"
            "       from the verified source JSON/CSV files in results/.",
            file=sys.stderr,
        )
        sys.exit(2)
    try:
        return json.loads(CANONICAL_PATH.read_text())
    except json.JSONDecodeError as exc:
        print(f"ERROR: CANONICAL_METRICS.json is not valid JSON: {exc}", file=sys.stderr)
        sys.exit(2)


def m(canon: dict, key: str) -> dict:
    """Look up a metric block. Returns {} if missing."""
    return canon.get("metrics", {}).get(key, {}) or {}


def check_files() -> list[tuple[str, bool, str]]:
    checks = [
        ("Canonical metrics file", CANONICAL_PATH),
        ("Full-cohort thesis dataset", ROOT / "data/processed_full_cohort/thesis_dataset.parquet"),
        ("Full-cohort token tensor", ROOT / "data/processed_full_cohort/tokens.npy"),
        ("Final Persian PDF", ROOT / "thesis/thesis_fa.pdf"),
        ("Defense slides PDF", ROOT / "thesis/defense_slides.pdf"),
        ("Exp1 table", TABLES / "exp1_results.csv"),
        ("Few-shot BEST json", RESULTS / "exp_fewshot_best.json"),
        ("Federated table", TABLES / "exp3_results.csv"),
        ("Critical figures folder", RESULTS / "figures"),
    ]
    return [(name, path.exists(), str(path.relative_to(ROOT))) for name, path in checks]


def write_summary(canon: dict, checks: list[tuple[str, bool, str]]) -> None:
    ok_count = sum(1 for _, ok, _ in checks if ok)

    tab = m(canon, "tabular_sota_test_auroc")
    stacked = m(canon, "stacked_best_auroc")
    fewshot = m(canon, "fewshot_best_auroc")
    rf = m(canon, "exp1_random_forest_auroc")
    prop = m(canon, "exp1_proposed_fewshot_auroc")
    cen = m(canon, "federated_centralized_auroc")
    fed = m(canon, "federated_federated_auroc")
    gap = m(canon, "federated_auroc_gap")

    lines = [
        "# Defense Run Summary",
        "",
        f"Generated: {ts()}",
        "",
        "> Auto-generated by `scripts/defense_demo.py`. Do not edit by hand.",
        f"> Canonical source: `{CANONICAL_PATH.relative_to(ROOT)}`",
        "",
        "## File Readiness",
        "",
    ]
    for name, ok, rel in checks:
        status = "PASS" if ok else "FAIL"
        lines.append(f"- {status}: {name} (`{rel}`)")

    lines.extend(
        [
            "",
            f"Readiness: {ok_count}/{len(checks)} checks passed.",
            "",
            "## Headline Numbers",
            "",
            "| Level | AUROC | Source |",
            "|-------|------:|--------|",
            f"| Tabular SOTA ceiling (`exp_tabular_sota.py`) | **{tab.get('display','?')}** | `{tab.get('source_file','?')}` |",
            f"| Stacked BEST (`exp_fewshot_best.py`) | **{stacked.get('display','?')}** {stacked.get('ci_display','')} | `{stacked.get('source_file','?')}` |",
            f"| Few-shot only BEST (`exp_fewshot_best.py`) | **{fewshot.get('display','?')}** {fewshot.get('ci_display','')} | `{fewshot.get('source_file','?')}` |",
            f"| Exp1 RandomForest (`exp1_main.py`) | **{rf.get('display','?')}** | `{rf.get('source_file','?')}` |",
            f"| Exp1 proposed low-shot model (`exp1_main.py`) | **{prop.get('display','?')}** | `{prop.get('source_file','?')}` |",
            f"| Federated centralized | {cen.get('display','?')} | `{cen.get('source_file','?')}` |",
            f"| Federated federated | {fed.get('display','?')} | `{fed.get('source_file','?')}` |",
            f"| Federated cost (gap) | **{gap.get('display','?')}** AUROC | `{gap.get('source_file','?')}` |",
            "",
            "## What to say (defensible script)",
            "",
            "Three lines, in order. Do not mix protocols.",
            "",
            f"1. **Tabular ceiling.** On the 2,000-patient MIMIC-IV cohort, the tuned classical pipeline reaches AUROC **{tab.get('display','?')}**. This is the practical ceiling for tabular feasibility prediction in this setting and explains why beating it with raw few-shot is hard.",
            f"2. **Stacked fusion is the deliverable.** The final stacked pipeline (few-shot probabilities + RF probabilities + ETHOS embeddings → meta-learner) reaches AUROC **{stacked.get('display','?')}** {stacked.get('ci_display','')}. That closes the gap to within {abs(round(float(tab.get('raw_value',0)) - float(stacked.get('raw_value',0)), 3))} of the ceiling.",
            f"3. **Raw few-shot under-performs RF — and that is honest.** Under the strict Exp1 protocol, the proposed low-shot model is **{prop.get('display','?')}** while RandomForest is **{rf.get('display','?')}**. We do *not* claim few-shot alone beats RF on tabular data. The scientific contribution is the federated + few-shot + classical *fusion*, plus the documented privacy cost of only ≈{gap.get('display','?')} AUROC for federation.",
            "",
            "## Interpretation (defense talking points)",
            "",
            "- **Why classical tabular models are strong:** small, structured, low-dimensional features favor tree-based models. The 2k MIMIC-IV cohort fits the regime where RF/XGBoost shine.",
            "- **Why raw few-shot can under-perform:** episodic training on a small tabular task does not benefit from the same priors that few-shot exploits in language/vision. Documenting this is more honest than hiding it.",
            "- **Why hybrid/fusion is the scientifically valuable answer:** a stacked meta-learner uses both the discriminative power of RF and the representation learned by ETHOS / few-shot. This is what closes the gap and is what we propose as the defensible deployment pattern.",
            "- **Why federated learning matters with a tiny gap:** a 0.005 AUROC cost in exchange for not centralizing patient records is an excellent trade in real hospital settings. Federation is about *deployability*, not solely about accuracy.",
            "",
            "## Defense Rule",
            "",
            "**Do not mix protocols.** Present Exp1 as the strict baseline comparison, and Stacked BEST as the final fusion pipeline. Use the rounding convention from `CANONICAL_METRICS.json` (3 decimal places; never use a slash-joined double-rounding display).",
            "",
        ]
    )
    SUMMARY_PATH.write_text("\n".join(lines))


def print_summary(canon: dict, checks: list[tuple[str, bool, str]]) -> None:
    tab = m(canon, "tabular_sota_test_auroc")
    stacked = m(canon, "stacked_best_auroc")
    fewshot = m(canon, "fewshot_best_auroc")
    rf = m(canon, "exp1_random_forest_auroc")
    prop = m(canon, "exp1_proposed_fewshot_auroc")
    cen = m(canon, "federated_centralized_auroc")
    fed = m(canon, "federated_federated_auroc")
    gap = m(canon, "federated_auroc_gap")

    print("\n=== DEFENSE DEMO SUMMARY ===")
    print(f"Canonical source: {CANONICAL_PATH.relative_to(ROOT)}\n")
    for name, ok, rel in checks:
        print(f"{'PASS' if ok else 'FAIL'}  {name}: {rel}")
    print("\nHeadline numbers (from CANONICAL_METRICS.json):")
    print(f"  Tabular SOTA ceiling           : AUROC {tab.get('display','?')}")
    print(f"  Stacked BEST                    : AUROC {stacked.get('display','?')} {stacked.get('ci_display','')}")
    print(f"  Few-shot only BEST              : AUROC {fewshot.get('display','?')} {fewshot.get('ci_display','')}")
    print(f"  Exp1 RandomForest               : AUROC {rf.get('display','?')}")
    print(f"  Exp1 proposed low-shot model    : AUROC {prop.get('display','?')}")
    print(f"  Federated centralized → federated: {cen.get('display','?')} → {fed.get('display','?')}  (gap {gap.get('display','?')})")
    print("\nCore sentence (defensible):")
    print(
        f"  Under the strict Exp1 protocol, few-shot alone (AUROC {prop.get('display','?')})\n"
        f"  is weaker than RandomForest ({rf.get('display','?')}). The final stacked pipeline\n"
        f"  reaches AUROC {stacked.get('display','?')} {stacked.get('ci_display','')}, closing\n"
        f"  most of the gap to the tabular ceiling ({tab.get('display','?')}). Federation costs\n"
        f"  only ≈{gap.get('display','?')} AUROC."
    )
    print(f"\nWrote: {SUMMARY_PATH.relative_to(ROOT)}")


def run_cmd(cmd: list[str]) -> int:
    print(f"\n[{ts()}] RUN: {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=ROOT).returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the thesis defense demo safely.")
    parser.add_argument(
        "--mode",
        choices=["summary", "quick", "full"],
        default="summary",
        help="summary reads canonical results; quick validates/regenerates assets; full runs high-value experiments.",
    )
    parser.add_argument(
        "--include-fewshot",
        action="store_true",
        help="In quick mode, also run exp_fewshot_best.py --quick. Avoid during live defense unless you have time.",
    )
    args = parser.parse_args()

    canon = load_canonical()

    if args.mode == "quick":
        rc = run_cmd([sys.executable, "results/validate_thesis_readiness.py"])
        if rc != 0:
            return rc
        rc = run_cmd([sys.executable, "scripts/build_thesis_assets.py"])
        if rc != 0:
            return rc
        if args.include_fewshot:
            rc = run_cmd([sys.executable, "-u", "experiments/exp_fewshot_best.py", "--quick"])
            if rc != 0:
                return rc
    elif args.mode == "full":
        rc = run_cmd([sys.executable, "-u", "scripts/run_value_experiments.py", "--figures"])
        if rc != 0:
            return rc

    checks = check_files()
    write_summary(canon, checks)
    print_summary(canon, checks)
    return 0 if all(ok for _, ok, _ in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
